In [5]:
import pandas as pd

# Read the Excel file
df = pd.read_excel('itemsrawmaterials.xlsx')

# Iterate through each row and update the database
for index, row in df.iterrows():
    item_code = row['item_code']
    name = row['name'].strip()
    
    # Update the meals.items table
    update_query = f'UPDATE meals.items SET itemCode = "{item_code}" WHERE Name = \'{name}\';'
    print(update_query)

UPDATE meals.items SET itemCode = "1" WHERE Name = 'Belcolade Dark Chocolate';
UPDATE meals.items SET itemCode = "2" WHERE Name = 'VANILLA POWDER';
UPDATE meals.items SET itemCode = "3" WHERE Name = 'VANILLA EXTRACT/ESSENCE';
UPDATE meals.items SET itemCode = "5" WHERE Name = 'BREAD IMPROVER';
UPDATE meals.items SET itemCode = "6" WHERE Name = 'ALMOND MILK UNSWEETNED';
UPDATE meals.items SET itemCode = "7" WHERE Name = 'VINEGAR APPLE CIDER';
UPDATE meals.items SET itemCode = "8" WHERE Name = 'VINEGAR BALSAMIC';
UPDATE meals.items SET itemCode = "9" WHERE Name = 'BEAN BLACK LOW SODIUM ( CAN)';
UPDATE meals.items SET itemCode = "10" WHERE Name = 'OIL PEANUT';
UPDATE meals.items SET itemCode = "11" WHERE Name = 'CAPER';
UPDATE meals.items SET itemCode = "12" WHERE Name = 'CHICKPEAS CAN  (LOW SODIUM )';
UPDATE meals.items SET itemCode = "13" WHERE Name = 'ARTICHOKE HEARTS';
UPDATE meals.items SET itemCode = "14" WHERE Name = 'SWEET CORN KERNEL';
UPDATE meals.items SET itemCode = "15" WHERE Name = 'NATURAL HONEY';
UPDATE meals.items SET itemCode = "16" WHERE Name = 'MAPLE SYRUP';
UPDATE meals.items SET itemCode = "17" WHERE Name = 'MUSTARD DIJON';
UPDATE meals.items SET itemCode = "18" WHERE Name = 'OIL OLIVE';
UPDATE meals.items SET itemCode = "19" WHERE Name = 'PINEAPPLE SLICE CAN';
UPDATE meals.items SET itemCode = "20" WHERE Name = 'DATES RAMADAN';
UPDATE meals.items SET itemCode = "21" WHERE Name = 'SRIRACHA SAUCE';
UPDATE meals.items SET itemCode = "22" WHERE Name = 'TOMATO PASTE LOW SODIUM';
UPDATE meals.items SET itemCode = "23" WHERE Name = 'GRENDAINEE MOLASSES';
UPDATE meals.items SET itemCode = "25" WHERE Name = 'VINEGAR WHITE';
UPDATE meals.items SET itemCode = "26" WHERE Name = 'VINEGAR RED';
UPDATE meals.items SET itemCode = "27" WHERE Name = 'VINEGAR RICE';
UPDATE meals.items SET itemCode = "28" WHERE Name = 'PINEAPPLE SYRUP';
UPDATE meals.items SET itemCode = "29" WHERE Name = 'RED CHILLI PASTE';
UPDATE meals.items SET itemCode = "30" WHERE Name = 'GHERKIN';
UPDATE meals.items SET itemCode = "31" WHERE Name = 'OIL SESAME/ACE';
UPDATE meals.items SET itemCode = "32" WHERE Name = 'CORN BABY';
UPDATE meals.items SET itemCode = "33" WHERE Name = 'BEAN WHITE CAN';
UPDATE meals.items SET itemCode = "34" WHERE Name = 'VINEGAR GRAPE';
UPDATE meals.items SET itemCode = "35" WHERE Name = 'MUSHROOM CAN';
UPDATE meals.items SET itemCode = "36" WHERE Name = 'COCONUT MILK UNSWEETENED';
UPDATE meals.items SET itemCode = "37" WHERE Name = 'PEANUT BUTTER FAT FREE';
UPDATE meals.items SET itemCode = "38" WHERE Name = 'KOREAN CHILLI PASTE';
UPDATE meals.items SET itemCode = "39" WHERE Name = 'AGAVE SYRUP';
UPDATE meals.items SET itemCode = "40" WHERE Name = 'VINEGAR RICE JAPANESE';
UPDATE meals.items SET itemCode = "42" WHERE Name = 'SAMBAL OELEK';
UPDATE meals.items SET itemCode = "43" WHERE Name = 'EXTRA VIRGIN OLIVE OIL';
UPDATE meals.items SET itemCode = "44" WHERE Name = 'OLIVE KALAMATA';
UPDATE meals.items SET itemCode = "45" WHERE Name = 'TAMARIND PASTE';
UPDATE meals.items SET itemCode = "46" WHERE Name = 'ROSE WATER';
UPDATE meals.items SET itemCode = "48" WHERE Name = 'RED CURRY PASTE AND SAUCE';
UPDATE meals.items SET itemCode = "49" WHERE Name = 'VINEGAR RICE CHINESE';
UPDATE meals.items SET itemCode = "50" WHERE Name = 'TOMATO PEELED (CAN)';
UPDATE meals.items SET itemCode = "51" WHERE Name = 'OLIVE SLICE BLACK';
UPDATE meals.items SET itemCode = "52" WHERE Name = 'RED KIDNEY BEANS';
UPDATE meals.items SET itemCode = "53" WHERE Name = 'DILL PICKLES SLICE';
UPDATE meals.items SET itemCode = "54" WHERE Name = 'Raspberry in light';
UPDATE meals.items SET itemCode = "55" WHERE Name = 'FLAXSEEDS OIL';
UPDATE meals.items SET itemCode = "56" WHERE Name = 'COCONUT WATER';
UPDATE meals.items SET itemCode = "57" WHERE Name = 'SOY MILK';
UPDATE meals.items SET itemCode = "58" WHERE Name = 'FOUL MEDAMAS';
UPDATE meals.items SET itemCode = "59" WHERE Name = 'SUSHI GINGER';
UPDATE meals.items SET itemCode = "60" WHERE Name = 'TRUFFLE OIL';
UPDATE meals.items SET itemCode = "61" WHERE Name = 'CUCUMBER PICKLE';
UPDATE meals.items SET itemCode = "62" WHERE Name = 'STRAWBERRY ESSENCE';
UPDATE meals.items SET itemCode = "63" WHERE Name = 'GREEN OLIVES';
UPDATE meals.items SET itemCode = "64" WHERE Name = 'Coconut oil';
UPDATE meals.items SET itemCode = "65" WHERE Name = 'YELLOW MUSTARD';
UPDATE meals.items SET itemCode = "66" WHERE Name = 'CANOLA OIL';
UPDATE meals.items SET itemCode = "67" WHERE Name = 'DRINKING WATER';
UPDATE meals.items SET itemCode = "69" WHERE Name = 'GRANOLA';
UPDATE meals.items SET itemCode = "70" WHERE Name = 'OATS OLD FASHIONED';
UPDATE meals.items SET itemCode = "71" WHERE Name = 'OLD FASHIONED ROLLED OATS';
UPDATE meals.items SET itemCode = "72" WHERE Name = 'OATS QUICK/QUACKER';
UPDATE meals.items SET itemCode = "73" WHERE Name = 'OATS STEEL CUT';
UPDATE meals.items SET itemCode = "74" WHERE Name = 'CORN FLAKES';
UPDATE meals.items SET itemCode = "75" WHERE Name = 'GLUTEN FREE QUICK OATS';
UPDATE meals.items SET itemCode = "76" WHERE Name = 'CREAM CHEESE';
UPDATE meals.items SET itemCode = "77" WHERE Name = 'MAYONAISE LIGHT HEINZ';
UPDATE meals.items SET itemCode = "78" WHERE Name = 'GRENADINE MOLASSES';
UPDATE meals.items SET itemCode = "79" WHERE Name = 'LABAN LOW FAT';
UPDATE meals.items SET itemCode = "80" WHERE Name = 'GOAT MILK';
UPDATE meals.items SET itemCode = "81" WHERE Name = 'WHIPPING CREAM';
UPDATE meals.items SET itemCode = "82" WHERE Name = 'BUTTER MILK LOW FAT';
UPDATE meals.items SET itemCode = "83" WHERE Name = 'CHEESE CHEDDAR LOW FAT';
UPDATE meals.items SET itemCode = "84" WHERE Name = 'CREAM COOKING LOW FAT';
UPDATE meals.items SET itemCode = "85" WHERE Name = 'CHEESE FETA LOW FAT';
UPDATE meals.items SET itemCode = "86" WHERE Name = 'YOGHURT  GREEK 0% FAT';
UPDATE meals.items SET itemCode = "87" WHERE Name = 'CHEESE HALLOUM LOW FAT';
UPDATE meals.items SET itemCode = "88" WHERE Name = 'CHEESE PROVOLONE LOW FAT';
UPDATE meals.items SET itemCode = "89" WHERE Name = 'CHEESE MOZZARELLA LOW FAT';
UPDATE meals.items SET itemCode = "90" WHERE Name = 'CHEESE PARMESAN LOW FAT';
UPDATE meals.items SET itemCode = "91" WHERE Name = 'CHEESE QUESO BLANCO LOW FAT';
UPDATE meals.items SET itemCode = "92" WHERE Name = 'MILK SKIM';
UPDATE meals.items SET itemCode = "93" WHERE Name = 'CHEESE GOAT LOW FAT';
UPDATE meals.items SET itemCode = "94" WHERE Name = 'SOUR CREAM LOW FAT';
UPDATE meals.items SET itemCode = "95" WHERE Name = 'LABNA NON FAT';
UPDATE meals.items SET itemCode = "96" WHERE Name = 'YOGHURT FULL FAT';
UPDATE meals.items SET itemCode = "97" WHERE Name = 'CHEESE RICOTTA LOW FAT';
UPDATE meals.items SET itemCode = "98" WHERE Name = 'CHEESE COTTAGE NON FAT';
UPDATE meals.items SET itemCode = "99" WHERE Name = 'CHEESE QUESO FRESCO LOW FAT';
UPDATE meals.items SET itemCode = "101" WHERE Name = 'ALMOND FLAKES';
UPDATE meals.items SET itemCode = "102" WHERE Name = 'BAKING POWDER NO SODIUM';
UPDATE meals.items SET itemCode = "103" WHERE Name = 'PEPPER BLACK';
UPDATE meals.items SET itemCode = "104" WHERE Name = 'CAYENNE PEPPER';
UPDATE meals.items SET itemCode = "105" WHERE Name = 'CHAT MASALA';
UPDATE meals.items SET itemCode = "106" WHERE Name = 'CINNAMON POWDER';
UPDATE meals.items SET itemCode = "107" WHERE Name = 'CORIANDER POWDER';
UPDATE meals.items SET itemCode = "108" WHERE Name = 'MUSHROOM SHITAKE';
UPDATE meals.items SET itemCode = "109" WHERE Name = 'CUMIN POWDER';
UPDATE meals.items SET itemCode = "110" WHERE Name = 'GARLIC POWDER';
UPDATE meals.items SET itemCode = "111" WHERE Name = 'ITALIAN HERB';
UPDATE meals.items SET itemCode = "112" WHERE Name = 'OREGANO';
UPDATE meals.items SET itemCode = "113" WHERE Name = 'PAPRIKA POWDER';
UPDATE meals.items SET itemCode = "114" WHERE Name = 'MUSHROOM DRY';
UPDATE meals.items SET itemCode = "115" WHERE Name = 'RAISIN';
UPDATE meals.items SET itemCode = "116" WHERE Name = 'SALT LOW';
UPDATE meals.items SET itemCode = "117" WHERE Name = 'SEA SALT';
UPDATE meals.items SET itemCode = "118" WHERE Name = 'ZATAR';
UPDATE meals.items SET itemCode = "119" WHERE Name = 'ROSEMARY DRY';
UPDATE meals.items SET itemCode = "120" WHERE Name = 'PEPPER WHITE';
UPDATE meals.items SET itemCode = "121" WHERE Name = 'CLOVE WHOLE';
UPDATE meals.items SET itemCode = "122" WHERE Name = 'SESAME SEEDS WHITE';
UPDATE meals.items SET itemCode = "123" WHERE Name = 'ONION POWDER';
UPDATE meals.items SET itemCode = "124" WHERE Name = 'GINGER POWDER';
UPDATE meals.items SET itemCode = "125" WHERE Name = 'CHILLI FLAKES';
UPDATE meals.items SET itemCode = "126" WHERE Name = 'BAY LEAVES';
UPDATE meals.items SET itemCode = "127" WHERE Name = 'Bread Crumb Whole wheat';
UPDATE meals.items SET itemCode = "128" WHERE Name = 'PAPRIKA SMOKED';
UPDATE meals.items SET itemCode = "129" WHERE Name = 'XANTHAN GUM GLUETEEN FREE';
UPDATE meals.items SET itemCode = "130" WHERE Name = 'CURRY POWDER';
UPDATE meals.items SET itemCode = "131" WHERE Name = 'BREAD CRUMB ITALIAN';
UPDATE meals.items SET itemCode = "132" WHERE Name = 'CAJUN SPICES';
UPDATE meals.items SET itemCode = "133" WHERE Name = 'MIX SPICES ( ITALIAN ) IN HOUSE';
UPDATE meals.items SET itemCode = "134" WHERE Name = 'SHAWARMA SPICES';
UPDATE meals.items SET itemCode = "135" WHERE Name = 'CARDAMOM POWDER';
UPDATE meals.items SET itemCode = "136" WHERE Name = 'MISTIKA POWDER';
UPDATE meals.items SET itemCode = "137" WHERE Name = 'CHIPOTLE CHILLI POWDER';
UPDATE meals.items SET itemCode = "138" WHERE Name = 'SAFFRON';
UPDATE meals.items SET itemCode = "139" WHERE Name = 'TURKISH SPICES';
UPDATE meals.items SET itemCode = "140" WHERE Name = 'PEPPERCORN';
UPDATE meals.items SET itemCode = "141" WHERE Name = 'SUMAK';
UPDATE meals.items SET itemCode = "142" WHERE Name = 'CHILLI POWDER';
UPDATE meals.items SET itemCode = "143" WHERE Name = 'TURMERIC POWDER';
UPDATE meals.items SET itemCode = "144" WHERE Name = 'ORANGE COLOR';
UPDATE meals.items SET itemCode = "145" WHERE Name = 'CLOVE POWDER';
UPDATE meals.items SET itemCode = "146" WHERE Name = 'WHOLE SPICES INDIAN';
UPDATE meals.items SET itemCode = "147" WHERE Name = 'BLACK LIME POWDER';
UPDATE meals.items SET itemCode = "148" WHERE Name = 'ARABIC SPICES';
UPDATE meals.items SET itemCode = "149" WHERE Name = 'RED SWEET PAPRIKA';
UPDATE meals.items SET itemCode = "150" WHERE Name = 'KASTURI METHI';
UPDATE meals.items SET itemCode = "151" WHERE Name = 'TANDOORI MASALA';
UPDATE meals.items SET itemCode = "152" WHERE Name = 'RED FOOD COLOR';
UPDATE meals.items SET itemCode = "153" WHERE Name = 'SAFFRON FOOD COLOR';
UPDATE meals.items SET itemCode = "154" WHERE Name = 'WONTON STRIPS';
UPDATE meals.items SET itemCode = "155" WHERE Name = 'CINNAMON WHOLE';
UPDATE meals.items SET itemCode = "156" WHERE Name = 'MIX HERB ITALIAN';
UPDATE meals.items SET itemCode = "157" WHERE Name = 'CHINESE 5 SPICE';
UPDATE meals.items SET itemCode = "158" WHERE Name = 'CRANBERRY DRY';
UPDATE meals.items SET itemCode = "159" WHERE Name = 'YEAST ACTIVE';
UPDATE meals.items SET itemCode = "160" WHERE Name = 'ALMOND WHOLE';
UPDATE meals.items SET itemCode = "161" WHERE Name = 'CARDAMOM WHOLE';
UPDATE meals.items SET itemCode = "162" WHERE Name = 'CHICKPEAS DRY 15mm';
UPDATE meals.items SET itemCode = "163" WHERE Name = 'BEEF BROTH(IN HOUSE)';
UPDATE meals.items SET itemCode = "164" WHERE Name = 'CORN STAR';
UPDATE meals.items SET itemCode = "165" WHERE Name = 'LEMON POWDER';
UPDATE meals.items SET itemCode = "166" WHERE Name = 'BIRYANI MASLA';
UPDATE meals.items SET itemCode = "167" WHERE Name = 'MEAT MASALA';
UPDATE meals.items SET itemCode = "168" WHERE Name = 'VEG BROTH';
UPDATE meals.items SET itemCode = "169" WHERE Name = 'CASSIA POWDER';
UPDATE meals.items SET itemCode = "170" WHERE Name = 'PEPPER BLACK WHOLE';
UPDATE meals.items SET itemCode = "171" WHERE Name = 'BABY CARROT';
UPDATE meals.items SET itemCode = "172" WHERE Name = 'OATS FLOUR';
UPDATE meals.items SET itemCode = "173" WHERE Name = 'RICE SYRUP';
UPDATE meals.items SET itemCode = "174" WHERE Name = 'COCOA POWDER';
UPDATE meals.items SET itemCode = "175" WHERE Name = 'COCONUT SUGAR';
UPDATE meals.items SET itemCode = "176" WHERE Name = 'COCONUT GRANOLA';
UPDATE meals.items SET itemCode = "177" WHERE Name = 'PLUM';
UPDATE meals.items SET itemCode = "178" WHERE Name = 'POPCORN SEEDS';
UPDATE meals.items SET itemCode = "179" WHERE Name = 'DRY FIG';
UPDATE meals.items SET itemCode = "180" WHERE Name = 'BI-CARBONATE SODA';
UPDATE meals.items SET itemCode = "181" WHERE Name = 'PUMPKIN SEED';
UPDATE meals.items SET itemCode = "182" WHERE Name = 'ROASTED PUMPKIN SEED';
UPDATE meals.items SET itemCode = "183" WHERE Name = 'RICE PAPER';
UPDATE meals.items SET itemCode = "184" WHERE Name = 'OIL COCONUT';
UPDATE meals.items SET itemCode = "185" WHERE Name = 'SUSHI RICE';
UPDATE meals.items SET itemCode = "187" WHERE Name = 'MISO PASTE';
UPDATE meals.items SET itemCode = "188" WHERE Name = 'JASMINE RICE';
UPDATE meals.items SET itemCode = "189" WHERE Name = 'HARISA PASTE';
UPDATE meals.items SET itemCode = "190" WHERE Name = 'PEARS';
UPDATE meals.items SET itemCode = "191" WHERE Name = 'VINE LEAVES';
UPDATE meals.items SET itemCode = "192" WHERE Name = 'BURGOL BROWN';
UPDATE meals.items SET itemCode = "193" WHERE Name = 'BEEF SAUSAGE';
UPDATE meals.items SET itemCode = "194" WHERE Name = 'BEEF FRANKS';
UPDATE meals.items SET itemCode = "195" WHERE Name = 'WHITE RICE';
UPDATE meals.items SET itemCode = "196" WHERE Name = 'BOB BREAD MIX GRAIN';
UPDATE meals.items SET itemCode = "199" WHERE Name = 'GOJIBERRY';
UPDATE meals.items SET itemCode = "200" WHERE Name = 'ARROWROOT';
UPDATE meals.items SET itemCode = "202" WHERE Name = 'EGYPTIAN RICE';
UPDATE meals.items SET itemCode = "204" WHERE Name = 'CHERRY DRY';
UPDATE meals.items SET itemCode = "205" WHERE Name = 'PLAIN FLOUR GLUTEEN FREE';
UPDATE meals.items SET itemCode = "206" WHERE Name = 'TACO SEASONING';
UPDATE meals.items SET itemCode = "207" WHERE Name = 'ITALIAN BROWN RICE';
UPDATE meals.items SET itemCode = "208" WHERE Name = 'GARAM MASALA';
UPDATE meals.items SET itemCode = "210" WHERE Name = 'ITALIAN PASTA';
UPDATE meals.items SET itemCode = "211" WHERE Name = 'GREEN CURRY PASTE';
UPDATE meals.items SET itemCode = "212" WHERE Name = 'ITALIAN SEASONING';
UPDATE meals.items SET itemCode = "213" WHERE Name = 'Plum Sauce';
UPDATE meals.items SET itemCode = "214" WHERE Name = 'OIL OLIVE SPRAY';
UPDATE meals.items SET itemCode = "216" WHERE Name = 'GLUTEN FREE SPAGHETTI';
UPDATE meals.items SET itemCode = "217" WHERE Name = 'GLUTEN FREE  EDAMAME SPAGHETTI';
UPDATE meals.items SET itemCode = "219" WHERE Name = 'DRY LEMON WHOLE';
UPDATE meals.items SET itemCode = "220" WHERE Name = 'DRY LEMON Powder';
UPDATE meals.items SET itemCode = "221" WHERE Name = 'MEAT TENDERIZER';
UPDATE meals.items SET itemCode = "222" WHERE Name = 'DRIED PINEAPPLE';
UPDATE meals.items SET itemCode = "223" WHERE Name = 'DRIED MANGO';
UPDATE meals.items SET itemCode = "224" WHERE Name = 'LENTIN GREEN/AMANAH';
UPDATE meals.items SET itemCode = "225" WHERE Name = 'fish sauce';
UPDATE meals.items SET itemCode = "226" WHERE Name = 'Round Black Container';
UPDATE meals.items SET itemCode = "227" WHERE Name = 'Rectangular Black Container';
UPDATE meals.items SET itemCode = "228" WHERE Name = 'RE 16 BLACK';
UPDATE meals.items SET itemCode = "229" WHERE Name = 'White Carrying Bag';
UPDATE meals.items SET itemCode = "230" WHERE Name = '30cmCling Film';
UPDATE meals.items SET itemCode = "231" WHERE Name = 'LUNCH BOX 3 COMP';
UPDATE meals.items SET itemCode = "232" WHERE Name = 'RECT 3 COMP ALUMINIUM CTNR';
UPDATE meals.items SET itemCode = "233" WHERE Name = 'LUNCH BOX SINGLE LB2 ECO';
UPDATE meals.items SET itemCode = "234" WHERE Name = 'ROUND PLASTIC CONTAINER 250 ML';
UPDATE meals.items SET itemCode = "235" WHERE Name = 'BLACK PPM/W BASE (COMBO 16OZ)';
UPDATE meals.items SET itemCode = "236" WHERE Name = 'ROUND BLACK M/W CTR WT LID (32 OZ # R0-32)';
UPDATE meals.items SET itemCode = "237" WHERE Name = 'Souffle Cup One Oz';
UPDATE meals.items SET itemCode = "238" WHERE Name = '10Oz CLEAR CONTAINER';
UPDATE meals.items SET itemCode = "239" WHERE Name = 'CLEAR CUP WT DOOM LID INSERT';
UPDATE meals.items SET itemCode = "240" WHERE Name = 'CLEAR CUP WT DOOM LID';
UPDATE meals.items SET itemCode = "241" WHERE Name = 'SNACK BOX RECTANGULAR BROWN';
UPDATE meals.items SET itemCode = "242" WHERE Name = 'CLING FILM  800*45';
UPDATE meals.items SET itemCode = "243" WHERE Name = 'ROUND CLEAR CONTAINER WLID';
UPDATE meals.items SET itemCode = "244" WHERE Name = 'CLEAR CUTLERY SET(HD)';
UPDATE meals.items SET itemCode = "245" WHERE Name = '(BIO107) LARGE RECTANGULAR CTN,950 ML';
UPDATE meals.items SET itemCode = "246" WHERE Name = '(BIO108) CLEAR LID FOR RECT CTN LRG';
UPDATE meals.items SET itemCode = "247" WHERE Name = '(BIO112) BIO DEGRADABLE RECT CTNB2 COMP 800ML';
UPDATE meals.items SET itemCode = "248" WHERE Name = '(BIO113) CLEAR DOME LID PP FOR RECT CTN 2-COMP';
UPDATE meals.items SET itemCode = "249" WHERE Name = 'SQUARE BOWL';
UPDATE meals.items SET itemCode = "250" WHERE Name = '(BIO117) CLEAR DOME LID FOR SQUARE BOWL';
UPDATE meals.items SET itemCode = "251" WHERE Name = 'OVAL ECO STREET BOWL';
UPDATE meals.items SET itemCode = "252" WHERE Name = '(BIO127) CLEAR DOME LID FOR OVAL BOWL';
UPDATE meals.items SET itemCode = "253" WHERE Name = 'Rectangular Black Container';
UPDATE meals.items SET itemCode = "254" WHERE Name = 'ALMOND FLOUR';
UPDATE meals.items SET itemCode = "255" WHERE Name = 'COCONUT FLOUR/POWDER';
UPDATE meals.items SET itemCode = "256" WHERE Name = 'FLOUR BROWN WHOLE WHEAT GLUTEN FREE';
UPDATE meals.items SET itemCode = "257" WHERE Name = 'WHITE FLOUR';
UPDATE meals.items SET itemCode = "258" WHERE Name = 'FLOUR BROWN';
UPDATE meals.items SET itemCode = "259" WHERE Name = 'GRAM FLOUR';
UPDATE meals.items SET itemCode = "260" WHERE Name = 'RICE FLOUR';
UPDATE meals.items SET itemCode = "261" WHERE Name = 'CORNMEAL WHOLE GRAIN';
UPDATE meals.items SET itemCode = "262" WHERE Name = 'CORNSTRACH CORN FLOUR';
UPDATE meals.items SET itemCode = "263" WHERE Name = 'BREAD CRUMB PANKO';
UPDATE meals.items SET itemCode = "264" WHERE Name = 'FLOUR BROWN WHOLE WHEAT';
UPDATE meals.items SET itemCode = "268" WHERE Name = 'GLUTEN FREE ALL PURPOSE FLOUR';
UPDATE meals.items SET itemCode = "269" WHERE Name = 'APPLE RED';
UPDATE meals.items SET itemCode = "270" WHERE Name = 'AVOCADO';
UPDATE meals.items SET itemCode = "271" WHERE Name = 'BANANA';
UPDATE meals.items SET itemCode = "272" WHERE Name = 'BLACKBERRY';
UPDATE meals.items SET itemCode = "273" WHERE Name = 'BLUEBERRY';
UPDATE meals.items SET itemCode = "274" WHERE Name = 'ORANGE';
UPDATE meals.items SET itemCode = "275" WHERE Name = 'RASPBERRY';
UPDATE meals.items SET itemCode = "276" WHERE Name = 'KIWI';
UPDATE meals.items SET itemCode = "277" WHERE Name = 'MANGO FRESH';
UPDATE meals.items SET itemCode = "278" WHERE Name = 'PUMPKIN RED';
UPDATE meals.items SET itemCode = "279" WHERE Name = 'SWEET MELON';
UPDATE meals.items SET itemCode = "280" WHERE Name = 'STRAWBERRY';
UPDATE meals.items SET itemCode = "281" WHERE Name = 'DRIED APRICOT';
UPDATE meals.items SET itemCode = "282" WHERE Name = 'PEACH';
UPDATE meals.items SET itemCode = "283" WHERE Name = 'COCONUT GREATED FRESH';
UPDATE meals.items SET itemCode = "284" WHERE Name = 'GRAPES GREEN';
UPDATE meals.items SET itemCode = "285" WHERE Name = 'MANDARIN';
UPDATE meals.items SET itemCode = "286" WHERE Name = 'ORANGE JUICE (IN HOUSE)';
UPDATE meals.items SET itemCode = "287" WHERE Name = 'FIG FRESH';
UPDATE meals.items SET itemCode = "288" WHERE Name = 'APPLE GREEN';
UPDATE meals.items SET itemCode = "289" WHERE Name = 'WATERMELON';
UPDATE meals.items SET itemCode = "290" WHERE Name = 'PINEAPPLE';
UPDATE meals.items SET itemCode = "291" WHERE Name = 'Pappaya';
UPDATE meals.items SET itemCode = "292" WHERE Name = 'POMEGRANATE';
UPDATE meals.items SET itemCode = "293" WHERE Name = 'CRANBERRY FRESH';